<%@ Page Title="Edit Categories" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EditCategories.aspx.cs" Inherits="Exam.WebForms.Admin.EditCategories" %>

<asp:Content ID="ContentEditCategories" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <h1><%: this.Title %></h1>
    </div>
    <div class="row">
        <asp:GridView runat="server" ItemType="Exam.WebForms.Models.Category" SelectMethod="GridViewCategories_Select"
            ID="GridViewCategories" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
            UpdateMethod="GridViewCategories_Update" DeleteMethod="GridViewCategories_Delete"
            AllowPaging="True" AllowSorting="True" PageSize="5" AutoGenerateColumns="False" DataKeyNames="Id">
            <Columns>
                <asp:BoundField DataField="Name" HeaderText="Category Name" SortExpression="Name" />
                <asp:CommandField ShowEditButton="true" ShowDeleteButton="true" HeaderText="Action" />
            </Columns>
        </asp:GridView>
    </div>

</asp:Content>
